### ISSUE TITLE
NET8 DeleteRangeAsync NRE

### ISSUE THREAD

**Issue by VitaliyChaban** [yangzhongke/Zack.EFCore.Batch#131]
![image](https://github.com/yangzhongke/Zack.EFCore.Batch/assets/95292018/839198da-18de-4097-93d5-74c560913ff5)
![image](https://github.com/yangzhongke/Zack.EFCore.Batch/assets/95292018/df2d9070-5bf0-4789-ac6a-5794260be9b4)

Package version: Include="Zack.EFCore.Batch.Npgsql_NET8" Version="8.1.8"
Core version: 8

Do you have this problem?
Maybe I'm doing something wrong?

**Comment by VitaliyChaban** [comment]
https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/Zack.EFCore.Batch/BatchEFExtensions.cs

175 line
#if (NET7_0_OR_GREATER)
            return default;
#else

This doesn't seem to allow the method to be executed.

**Comment by yangzhongke** [comment]
Since EFCore 7/8 has built-in support of 'batch update and delete' ([please see this page](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew?WT.mc_id=DT-MVP-5004444#executeupdate-and-executedelete-bulk-updates)), this library doesn't support EFCore 7 and higher anymore), but BulkInsert is still supported.

[Details](https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/README_NET7.md)

**Comment by yangzhongke** [comment]
https://github.com/yangzhongke/Zack.EFCore.Batch/blob/main/Zack.EFCore.Batch.MSSQL/ServiceCollectionExtensions.cs
Exception is thrown here when AddBatchEF_XX() is called.
