### ISSUE TITLE
NET6正式版了，希望更新到NET6正式版的

### ISSUE THREAD

**Issue by Coflys** [yangzhongke/Zack.EFCore.Batch#39]

**Comment by yangzhongke** [comment]
谢谢，最近在为新写的.NET6的书收尾，等交稿之后我就弄。

**Comment by Coflys** [comment]
好的，感谢

**Comment by yangzhongke** [comment]
最近在忙，忙过了这阵子我在弄吧，你有时间的话你可以自己研究一下。

**Comment by yangzhongke** [comment]
已经完成.NET 6的支持。.NET 6和.NET 5用的包不同，包名后面需要加_NET6：
Postgresql: Install-Package Zack.EFCore.Batch.MSSQL_NET6
SQLServer: Install-Package Zack.EFCore.Batch.MSSQL_NET6
MySQL: Install-Package Zack.EFCore.Batch.MySQL.Pomelo_NET6
Postgresql: Install-Package Zack.EFCore.Batch.Npgsql_NET6
Sqlite: Install-Package Zack.EFCore.Batch.Sqlite_NET6
Oracle: Not supported at this time, because there is no offical Oracle EF Core 6 Provider.

**Comment by yangzhongke** [comment]
感谢回复，请反馈测试结果。
