### ISSUE TITLE
是否支持联表更新或删除。

### ISSUE THREAD

**Issue by Harbor77** [yangzhongke/Zack.EFCore.Batch#40]
环境 .NET 5 + SQL Server 

比如sql 中的 联表更新
UPDATE TableA  SET  Column1= '测试'
FROM  TableB  AS  A 
INNER JOIN TableA  AS B ON  A.ID = B.ID
WHERE  A.Type ='A'  AND B.SType = 'B'

尝试在linq中写 
    ctx.BatchUpdate<表1>()
    .Set(a => a.Column1, a => "测试")
    .Where(a =>  a.Type  == "A")
    .Where(a =>  ctx.TableB.Where(b => b.ID  == a.ID && b.SType == "B").Any())
    .ExecuteAsync();
会报错 The count of columns should be even.

**Comment by yangzhongke** [comment]
谢谢反馈，忙过了下周，我会看一下。

**Comment by 77Harbor** [comment]
好的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangzhongke/Zack.EFCore.Batch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月13日(星期六) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangzhongke/Zack.EFCore.Batch] 是否支持联表更新或删除。 (Issue #40)





 
谢谢反馈，忙过了下周，我会看一下。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangzhongke** [comment]
bug 已修复，请更新到最新版。请反馈测试结果。谢谢。_

**Comment by 77Harbor** [comment]
更新到最新版本1.5.3后
测试后不报错了，但是sql语句生成的有问题，
生成sql 如下：
Update [表1] SET [Flag] = N'1'
WHERE EXISTS (
&nbsp; &nbsp; SELECT 1
&nbsp; &nbsp; FROM [表2]
&nbsp; &nbsp; WHERE [ID] = [ID])

这样条件没有起到作用
想要的应该是：
Update [表1] SET [Flag] = N'1'
WHERE EXISTS (
&nbsp; &nbsp; SELECT 1
&nbsp; &nbsp; FROM [表2]
&nbsp; &nbsp; WHERE [ID] =&nbsp;[表1].[ID])



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yangzhongke/Zack.EFCore.Batch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月1日(星期三) 晚上11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yangzhongke/Zack.EFCore.Batch] 是否支持联表更新或删除。 (Issue #40)





 
bug 已修复，请更新到最新版。请反馈测试结果。谢谢。_
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangzhongke** [comment]
谢谢反馈

**Comment by yangzhongke** [comment]
抱歉，受限于新的实现机制，无法支持复杂的级联更新。请拆分成先查询后更新

**Comment by Harbor77** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 中午1:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangzhongke/Zack.EFCore.Batch] 是否支持联表更新或删除。 (Issue #40)





 
抱歉，受限于新的实现机制，无法支持复杂的级联更新。请拆分成先查询后更新
