### ISSUE TITLE
Exception on Migration when using Npgsql version 6.0.5

### ISSUE THREAD

**Issue by begerard** [yangzhongke/Zack.EFCore.Batch#75]
Hi,

In the latest version of Npgsql (6.0.5) they renamed the internal class **NpgsqlOptions** to **NpgsqlSingletonOptions**, which throw an exception on call to **context.Database.Migrate();** when this library is also used (with **UseBatchEF_Npgsql**).

Here the investigation of Roji: https://github.com/npgsql/efcore.pg/issues/2407

And a short repro: https://github.com/begerard/ReproEfBatch

**Comment by yangzhongke** [comment]
Thanks for your feedback, I'll fix it ASAP.

**Comment by begerard** [comment]
Hey @yangzhongke

6.0.6 is due tomorrow, any new on your fix so we can resume updating .Net?
Need a PR? The change should not be hard if it's only a rename (only compatibility could be tricky).

**Comment by yangzhongke** [comment]
I'm sorry for the late reply.
Because I moved to New Zealand last month, I have tons of things to do, like renting a house, buying furniture, enrolments of my kids, etc. I haven't had time to deal with this for the last ten days.
If possible, could you create a PR? The most important thing is compatibility, the library should work well with both the old version of Npgsql and the new version, maybe detecting the version of Npgsql at runtime and calling NpgsqlOptions or  NpgsqlSingletonOptions through reflection is a possible way.

**Comment by yangzhongke** [comment]
Or we can add some codes to check the version of Npgsql, if the Npgsql is the new 'NpgsqlSingletonOptions' version, an exception 'This library is not compatible with the version of Npgsql, Please update the library to the latest version or downgrade the Npgsql to  6.0.4.'  would be thrown, and set the max version of Npgsql in the dependence settings. And then, I would publish a NuGet package. And then, we update the version of Npgsql to the latest in the following versions.

**Comment by yangzhongke** [comment]
Oh, I'll not bother you with it, I'll work on it today.

**Comment by yangzhongke** [comment]
Bug fixed, please update it to the latest version.

**Comment by begerard** [comment]
Update deployed and everything works fine, thanks !
